### ISSUE TITLE
Site down

### ISSUE THREAD

**Issue by yaronchristiaens** [jermbo/SampleAPIs#149]
I'm sorry to submit so many issues, but the site is down. Is it maybe possible to display a message when you work on the website? This way the users know that the website will be up again soon.

**Comment by thedamian** [comment]
SampleAPIs.com seems to be up:
https://downforeveryoneorjustme.com/sampleapis.com?proto=https

When we are working on the website we have a test version that we work on. If it's a day of the week that ends with Y the website should be up.

**Comment by yaronchristiaens** [comment]
That's weird, I have the following screen:

![image](https://user-images.githubusercontent.com/91212195/145469348-d98a0157-834f-45b8-a55e-b6bcccedaae7.png)

**Comment by molinto** [comment]
Down again for me

**Comment by thedamian** [comment]
Sample APIs front page was down from Jan 3rd (when I added the Jokes API and also updated the server hosting the website) until Jan 5th.  

This resoled on the API side of things (backend) still being available but the front end (the www. of the sampleapi empire) showing that there is no apis available. 

The issue was that I had added the backend changes (see latest commit) and pulled the latest on the production web server but had not built the front end correctly. Also the React 17 engine might have caused an issue (on the server it's reverted to 16.8) 

Regardless a new frontend build was completed successfully and published to the https://sampleapis.com website.

The https://api.sampleapis.com backend was never down and now contains a list of bad jokes. 

This issue has been resolved now (on Jan 5th) and I'm closing this issue with a big thanks to @yaronchristiaens  and @molinto for reminding us that it was down.
